// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_prefs.proto
// Protobuf Java Version: 4.27.3

package com.example.datastore.v1;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>bool isMarried = 3;</code>
   * @return The isMarried.
   */
  boolean getIsMarried();
}
